name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api:
    name: API E2E (Device Lab)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright API tests (HTML report)
        env:
          PLAYWRIGHT_HTML_REPORT: playwright-report
        run: npx playwright test tests/api.spec.ts --reporter=html
      - name: Upload API Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-api
          path: playwright-report

  ui:
    name: UI E2E (Railway)
    runs-on: ubuntu-latest
    needs: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Check BASE_URL secret exists
        run: |
          test -n "${{ secrets.RAILWAY_BASE_URL }}" || (echo "ERROR: RAILWAY_BASE_URL secret is missing" && exit 1)
      - name: Probe live site (3 attempts)
        run: |
          for i in 1 2 3; do
            if curl -sSf -I "${{ secrets.RAILWAY_BASE_URL }}" > /dev/null; then exit 0; fi
            sleep 5
          done
          echo "ERROR: Live site not reachable"
          exit 1
      - name: Run Playwright UI tests (HTML report)
        env:
          BASE_URL: ${{ secrets.RAILWAY_BASE_URL }}
          PLAYWRIGHT_HTML_REPORT: playwright-report
        run: npx playwright test tests/video.spec.ts --reporter=html
      - name: Upload UI Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-ui
          path: playwright-report
